spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: 2.0

contact:
  name: "Easy Bank Account Support"
  email: "support@easybank.com"
  address: "321, QA street, ABC 54321"
  support:
    - "666 323232"
    - "777 343434"